# Content for The Naga Report, edition 001, Monday 21 September 2026
# Style: no em dashes. Short hard grafs. Every figure traceable to a source below.

REPORT = dict(
    edition="001",
    date_long="Monday, 21 September 2026",
    date_iso="2026-09-21",
    day_of_war="1,671",
    cutoff="Data cut: 08:00 Kyiv (05:00 UTC), 21 Sep 2026. Window: 24 hrs unless stated.",
    risk="HIGH",
    risk_note="Nationwide strike drone pressure, 10 regions hit overnight, rail network degraded. No ballistic or cruise missile wave in the window.",
    bottom_line=[
        "A 172-drone night across 10 regions followed Ukraine's record strike on Moscow. Zaporizhzhia took the worst of it: apartment blocks, a university building and a shopping centre hit, 8 wounded in the oblast over the past day.",
        "At least 6 killed and 38 wounded nationwide in the past day (Kyiv Independent tally). Deaths in Sumy, Kharkiv (Lozova) and Donetsk oblasts.",
        "The rail network is the travel story: dozens of passenger trains delayed, worst cases past 16 hours, amid systematic attacks on the network including strikes at Lozova and Vinnytsia.",
        "Front: 238 combat clashes, Kostiantynivka and Pokrovsk the hottest axes. ISW logs no confirmed advances by either side on 20 Sep; Ukraine's 3rd Army Corps claims three villages northwest of Lyman.",
        "Diplomacy: Trump and Zelensky meet in New York on Tuesday at UNGA. Moscow's preliminary count gives United Russia 355 seats; certification is expected by Friday.",
    ],
    key_numbers=[
        ("172", "strike UAVs launched overnight"),
        ("147", "drones neutralized plus 1 Banderol"),
        ("238", "combat clashes at the front"),
        ("6 / 38", "civilians killed / wounded, 24h"),
        ("10", "regions hit overnight"),
        ("16h+", "worst passenger rail delay"),
    ],
    overnight=dict(
        title="Overnight air attack, 20 to 21 Sep",
        body=[
            "From 18:00 on 20 Sep Russia launched 172 strike UAVs (Shahed types including about 64 jet-powered, plus Gerbera and Parodiya decoys) and one S8000 Banderol guided missile-drone.",
            "Ukrainian Air Force, 08:00 report: 147 drones and the Banderol shot down or suppressed by EW. Hits recorded at 14 locations, debris at 4 more. The attack was still in progress when the report was issued.",
            "Launch areas: Belgorod, Shatalovo, Oryol, Kursk, Primorsko-Akhtarsk and Millerovo in Russia; occupied Donetsk; Hvardiiske in Crimea.",
            "No ballistic or cruise missiles reported in this window. Kyiv Independent gives 148 intercepted; we use the Air Force figure of 147.",
        ],
        srcs=[1, 2, 3],
    ),
    oblasts=[
        dict(name="Kyiv City", level="MED", text="Drone attack on the evening of 20 Sep. A woman was injured in Sviatoshynskyi district at about 18:00. Later, UAV debris fell at two sites in Holosiivskyi district near residential buildings; one car damaged, no fire.", srcs=[4, 5, 36]),
        dict(name="Kyiv Oblast", level="HIGH", text="Daytime drone strikes on 20 Sep damaged an industrial warehouse in Boyarka and a private enterprise in Novosilky. The Ventilation Systems plant in Boyarka lost its main production and warehouse buildings on the night of 19 to 20 Sep. The oblast death toll from the 19 to 20 Sep attacks stands at four, including three children, after the Hlevakha house strike in Fastiv district.", srcs=[6, 7, 8, 37]),
        dict(name="Chernihiv", level="LOW", text="Drone strike on an agricultural enterprise in Semenivka destroyed a hangar and damaged machinery. No casualties reported.", srcs=[3]),
        dict(name="Sumy", level="HIGH", text="Drones struck near an apartment block in Sumy city on the evening of 20 Sep: one woman killed, a 41-year-old man wounded, five vehicles damaged (Governor Hryhorov). Oblast total for the day per Kyiv Independent: 2 killed, 3 wounded including a 14-year-old girl. Regional digest: almost 60 attacks on 17 settlements in the 24 hours to the morning of 20 Sep.", srcs=[9, 3, 10]),
        dict(name="Kharkiv", level="HIGH", text="Lozova, overnight: a drone attack killed one woman and wounded three, including a 13-year-old boy with severe burns. A separate strike hit Lozova railway station; no passengers or staff hurt, all were in shelter. Ukrzaliznytsia will begin repairs when security allows. Oblast total: 1 killed, 5 wounded.", srcs=[11, 12, 3]),
        dict(name="Donetsk", level="HIGH", text="3 killed, 12 wounded in the past day. On 20 Sep a strike on a Kramatorsk evacuation centre killed 1 and injured 3. 583 people were evacuated from the oblast in a single day.", srcs=[3, 10]),
        dict(name="Dnipropetrovsk", level="MED", text="Among the 10 regions hit overnight (PM Koretskyi), no detail given. One wounded in the past day (a 20-year-old woman). One victim of the 3 Sep attack died of injuries. The 19 Sep late-evening strike on a Dnipro shopping mall injured five.", srcs=[3, 13, 14]),
        dict(name="Zaporizhzhia", level="SEVERE", text="Hardest hit overnight. Drones struck multi-storey apartment blocks, a university building and a shopping centre in Zaporizhzhia city; fire in a high-rise; more than 10 flats destroyed and 15 apartment buildings damaged in Oleksandrivskyi district (PM Koretskyi). Overnight wounded rose through the morning from 1 to 5 to 6; Kyiv Independent puts the oblast's past-day total at 8. No deaths reported. Regional digest for 19 Sep: 920-plus strikes on 55 settlements.", srcs=[3, 13, 15, 16]),
        dict(name="Kherson", level="HIGH", text="Air, drone and artillery strikes on dozens of settlements including Kherson city, Antonivka, Bilozerka, Stanislav, Beryslav and Novovorontsovka. 7 injured (regional tally; Kyiv Independent gives 9). Damage to 2 apartment blocks, 6 houses, a Catholic church, a museum, a bank, a supermarket and a gas pipeline.", srcs=[17, 3]),
        dict(name="Mykolaiv", level="MED", text="Listed among the 10 regions hit overnight. No casualty or damage detail confirmed at cut-off.", srcs=[13]),
        dict(name="Odesa", level="MED", text="A supermarket warehouse struck overnight, no casualties. Russian MoD claims hits on a bulk carrier at Odesa port, port infrastructure at Izmail and a second bulk carrier en route to Odesa. Unverified.", srcs=[3, 18]),
        dict(name="Poltava", level="MED", text="Late item, 13:17 Kyiv: a drone struck a critical infrastructure facility in Poltava district and started a fire; no casualties reported initially (Governor Diakivnych).", srcs=[38]),
        dict(name="Central and West", level="LOW", text="Rivne and Kirovohrad named among the 10 regions hit, no detail. Vinnytsia: drone strike damaged a railway infrastructure facility on the morning of 20 Sep, fire extinguished, no casualties.", srcs=[13, 19]),
    ],
    front=dict(
        title="Front line",
        body=[
            "General Staff, as of 08:00 on 21 Sep: 238 combat clashes, up from 211 the previous day. Heaviest fighting on the Kostiantynivka axis (24) and Pokrovsk (19), then Lyman (15), South Slobozhanshchyna (7), Kupiansk (6), North Slobozhanshchyna and Kursk (6), Sloviansk (5), Huliaipole (2), Orikhiv (2).",
            "Russian fires over the same period: 91 airstrikes, 295 guided bombs, 10,237 kamikaze drones, 2,903 shellings including 35 MLRS salvoes. Claimed Russian losses: 1,660 personnel, 3 air defence systems.",
            "ISW (20 Sep assessment): no confirmed advances by either side. Ukraine's 3rd Army Corps reports liberating Shandryholove, Derylove and Drobysheve northwest of Lyman under the second phase of Operation Vivaldi.",
        ],
        srcs=[20, 10, 21],
    ),
    ua_strikes=dict(
        title="Ukrainian long-range strikes",
        body=[
            "The headline event sits just before the window: the night of 19 to 20 Sep, final day of Duma voting, Ukraine's largest-ever attack on Moscow. Russian MoD claims 1,110 fixed-wing drones downed across about 20 regions, Crimea and the Black Sea; Sobyanin claims 450 downed en route to Moscow. Confirmed: the Moscow Oil Refinery damaged and burning. Moscow region governor Vorobyov: 2 killed, about 20 injured (CNN reports 3 killed).",
            "Zelensky confirmed strikes on a major oil facility and a logistics site in Moscow region. Zelensky's weapons list included the Pelican ballistic missile alongside Flamingo cruise missiles and multiple drone types; Kyiv Post notes Pelican's stated range makes a direct Moscow hit improbable, so its role is unclear. The General Staff also reports hits on a Buk-M3 and a Nebo-U radar.",
            "For the night of 20 to 21 Sep, no Russian MoD intercept claim or General Staff-confirmed strike was found at cut-off.",
        ],
        srcs=[22, 23, 24, 25, 39],
    ),
    naval=dict(
        title="Naval picture",
        body=[
            "No Ukrainian Navy ship count for 21 Sep was available in English at cut-off.",
            "Standing picture (Navy spokesman Pletenchuk, 14 Sep): for a fourth month Russia launches Kalibrs from inside harbours rather than putting carriers to sea. Up to four potential carriers in theatre (2 Buyan-M corvettes, 2 Varshavyanka submarines), realistically two active surface vessels. Two Kalibr launches so far in September.",
        ],
        srcs=[26],
    ),
    travel=dict(
        title="Travel, rail, energy",
        items=[
            ("RAIL", "Ukrzaliznytsia, 21 Sep morning: dozens of passenger trains delayed from 20 minutes to more than 16 hours. Worst: Mykolaiv to Kyiv +16h33, Mykolaiv to Lviv +12h40, Kryvyi Rih to Chernivtsi and to Rakhiv +11h58, Dnipro to Uzhhorod +10h36. Kyiv to Warsaw about +3h. Lozova station struck overnight; Vinnytsia rail infrastructure hit 20 Sep.", [27, 28, 11]),
            ("POWER", "Ukrenergo: no consumption restrictions planned for 21 Sep, none over the weekend. Advice stands to run heavy appliances in daylight hours.", [29]),
            ("BORDER", "No Ukrainian border-crossing disruptions found for the window. Russia's FSB has closed its side of the border opposite Narva, Estonia, from 16 to 26 Sep.", [21]),
            ("FX", "NBU official rate for 21 Sep: UAH 44.67 per USD.", [30]),
        ],
    ),
    headlines=[
        ("Ukraine fires 1,000-plus drones at Russia, largest-ever attack on Moscow, refinery hit", "PBS / AP", 22),
        ("Moscow targeted by Ukraine's largest drone attack on final day of election", "CNN", 31),
        ("Zelensky confirms strikes on key oil facility in Moscow region", "Ukrinform", 23),
        ("Russian attacks kill at least 6, wound 38; shopping mall hit in Zaporizhzhia", "Kyiv Independent", 3),
        ("Russia hits civilian infrastructure in 10 regions overnight, PM Koretskyi", "Ukrinform", 13),
        ("Russian forces strike Lozova railway station", "Ukrinform", 11),
        ("238 clashes; Kostiantynivka and Pokrovsk hottest", "Ukrinform", 20),
        ("ISW: 3rd Army Corps liberates three villages northwest of Lyman", "Kyiv Post / ISW", 21),
        ("Trump to meet Zelensky in New York as attacks intensify; Umerov says stumbling blocks down to one or two", "Axios", 32),
        ("Zelensky-Trump meeting follows Trump signing the Russia sanctions bill", "The Week", 33),
        ("United Russia takes 355 seats on record 59.3% turnout, largest-ever Duma faction", "Meduza", 34),
        ("Russia election results: what we know; Kyiv calls vote in occupied regions illegal", "Al Jazeera", 35),
        ("Kyiv region death toll rises to four including three children", "Ukrinform", 8),
        ("Ukrzaliznytsia: dozens of trains delayed up to 16h amid attacks", "UNN", 27),
        ("Russian MoD claims strikes on bulk carriers and port infrastructure at Odesa and Izmail (unverified)", "TASS", 18),
    ],
    watch=[
        "Tue 22 Sep: Trump and Zelensky meet at UNGA, New York.",
        "By Fri 25 Sep: Central Election Commission expected to certify Duma results.",
        "Russian response to the Moscow strike: no ballistic or cruise wave yet in this window; watch for one.",
        "Zaporizhzhia casualty figures: still rising at cut-off.",
    ],
    sources=[
        (1, "Ukrinform, Air defense neutralizes Banderol missile, 147 Russian drones overnight, 21 Sep", "https://www.ukrinform.net/rubric-ato/4166165-air-defense-neutralizes-banderol-missile-147-russian-drones-used-to-attack-ukraine-overnight.html"),
        (2, "Interfax-Ukraine, overnight attack summary, 21 Sep", "https://en.interfax.com.ua/news/general/1207254.html"),
        (3, "Kyiv Independent, Russian attacks kill at least 6, wound 38, 21 Sep", "https://kyivindependent.com/russian-attacks-kill-at-least-6-wound-38-across-ukraine-as-overnight-strike-hit-shopping-mall-in-zaporizhzhia/"),
        (4, "Ukrinform, UAV debris in Kyiv's Holosiivskyi district, 20 Sep", "https://www.ukrinform.net/rubric-ato/4166081-debris-from-russian-uavs-falls-near-residential-buildings-in-kyivs-holosiivskyi-district.html"),
        (5, "Mezha, Kyiv mayor on injured resident, 20 Sep", "https://mezha.net/eng/news/5964e394_kyiv_mayor_vitali/"),
        (6, "Ukrinform, Kyiv oblast drone damage, 20 Sep", "https://www.ukrinform.net/rubric-ato/4165982-drone-attack-on-kyiv-region-industrial-warehouse-damaged-in-boyarka-private-enterprise-hit-in-novosilky.html"),
        (7, "NV, drone strike kills woman and two children in Kyiv oblast, 20 Sep", "https://english.nv.ua/russian-war/russian-drone-strike-kills-woman-and-two-3-year-old-children-in-kyiv-oblast-50642926.html"),
        (8, "Ukrinform, Kyiv region death toll rises to four, 20 Sep", "https://www.ukrinform.net/rubric-ato/4165910-death-toll-from-russian-attacks-on-kyiv-region-rises-to-four-including-three-children.html"),
        (9, "Censor.net, Hryhorov on drone strike in Sumy, 20 Sep", "https://censor.net/en/news/4024389/oleh-hryhorov-reported-a-drone-strike-on-sumy"),
        (10, "Ukrainian Women's Guard, war digest for 20 Sep 2026", "https://uavarta.org/en/war-in-ukraine-today-latest-news-20-september-2026-photo/"),
        (11, "Ukrinform, Russian forces strike Lozova railway station, 21 Sep", "https://www.ukrinform.net/rubric-ato/4166181-russian-forces-strike-railway-station-in-lozova.html"),
        (12, "Mezha, Russian drones strike Lozova, 21 Sep", "https://mezha.net/eng/news/c9b32050_russian_drones_strike/"),
        (13, "Ukrinform, PM Koretskyi: civilian infrastructure hit in 10 regions, 21 Sep", "https://www.ukrinform.net/rubric-ato/4166291-russia-massively-attacks-civilian-infrastructure-in-10-ukrainian-regions-overnight-pm-koretskyi.html"),
        (14, "Ukrinform, Dnipro shopping mall strike, 19 Sep", "https://www.ukrinform.net/rubric-ato/4165855-russian-strike-on-shopping-mall-in-dnipro-leaves-five-injured.html"),
        (15, "UNN, Zaporizhzhia injured count rises to 5, 21 Sep", "https://unn.ua/en/news/the-number-of-people-injured-in-the-overnight-attack-on-zaporizhzhia-has-risen-to-5"),
        (16, "United24 Media, Zaporizhzhia homes, university and shopping centre hit, 21 Sep", "https://united24media.com/war-in-ukraine/russian-drones-hit-homes-university-and-shopping-center-in-zaporizhzhia-injuring-six-22709"),
        (17, "MOST, Kherson oblast daily casualty report, 21 Sep", "https://most.ks.ua/en/news/url/na-hersonschini-za-dobu-cherez-rosijski-obstrili-poraneni-7-ljudej/"),
        (18, "TASS, Russian MoD claims on Odesa and Izmail, 21 Sep (unverified)", "https://tass.com/politics/2190407"),
        (19, "Ukrinform, Vinnytsia rail infrastructure strike, 20 Sep", "https://www.ukrinform.net/rubric-ato/4165911-russian-drone-strike-hits-railway-infrastructure-in-vinnytsia-region.html"),
        (20, "Ukrinform, General Staff: 238 clashes, 21 Sep", "https://www.ukrinform.net/rubric-ato/4166160-war-update-238-clashes-at-front-over-past-day-with-heaviest-fighting-in-kostiantynivka-and-pokrovsk-directions.html"),
        (21, "Kyiv Post, ISW assessment for 20 Sep", "https://www.kyivpost.com/post/84971"),
        (22, "PBS / AP, Ukraine fires over 1,000 drones at Russia, 20 Sep", "https://www.pbs.org/newshour/world/ukraine-fires-over-1000-drones-at-russia-including-largest-ever-attack-on-moscow"),
        (23, "Ukrinform, Zelensky confirms strikes on Moscow-region oil facility, 20 Sep", "https://www.ukrinform.net/rubric-ato/4165935-zelensky-confirms-strikes-on-key-oil-industry-facility-in-moscow-region.html"),
        (24, "TASS, Russian MoD intercept claims, 20 Sep", "https://tass.com/defense/2190245"),
        (25, "Ukrinform, General Staff on Buk-M3 and Nebo-U hits, 20 Sep", "https://www.ukrinform.net/rubric-ato/4165980-ukrainian-defense-forces-strike-russian-airdefense-systems-radar-and-drone-command-posts.html"),
        (26, "Ukrinform, Navy: Russia launches Kalibrs without sending vessels to sea, 14 Sep", "https://www.ukrinform.net/rubric-ato/4163892-russian-forces-launch-kalibr-missiles-without-sending-launch-vessels-to-sea-navy.html"),
        (27, "UNN, dozens of trains delayed up to 16 hours, 21 Sep", "https://unn.ua/en/news/up-to-16-hours-of-waiting-dozens-of-trains-are-running-with-delays-amid-russian-attacks"),
        (28, "Korabelov, Mykolaiv trains top the delay rankings, 21 Sep", "https://korabelov.info/en/2026/09/617385/trains-from-mykolaiv-topped-the-delay-rankings-the-delay-exceeded-16-hours/"),
        (29, "Mezha, Ukrenergo: no restrictions planned, 21 Sep", "https://mezha.net/eng/news/e5bbea39_ukrenergo_says_ukraine/"),
        (30, "Mezha, NBU official rate for 21 Sep", "https://mezha.net/eng/news/7c40f6f4_ukraine-s_central_bank/"),
        (31, "CNN, Moscow targeted on final day of election, 20 Sep", "https://www.cnn.com/2026/09/20/europe/moscow-ukraine-attack-russia-election"),
        (32, "Axios, Trump to meet Zelensky in New York, 20 Sep", "https://www.axios.com/2026/09/20/trump-zelensky-meeting-russia-ukraine-war-talks"),
        (33, "The Week, Zelensky-Trump New York meeting, 21 Sep", "https://www.theweek.in/news/middle-east/2026/09/21/zelenskyy-trump-new-york-meeting.html"),
        (34, "Meduza, United Russia secures 355 seats, 21 Sep", "https://meduza.io/en/news/2026/09/21/united-russia-secures-constitutional-majority-in-state-duma-with-355-seats-as-election-officials-report-record-59-turnout"),
        (35, "Al Jazeera, Russia election results: what we know, 21 Sep", "https://www.aljazeera.com/news/2026/9/21/russia-election-results-show-putins-party-winning-what-we-know"),
        (36, "Censor.net, woman injured in Kyiv's Sviatoshynskyi district, 20 Sep", "https://censor.net/en/news/4024374/russian-attack-on-kyiv-a-woman-has-been-injured-in-the-sviatoshynskyi-district"),
        (37, "Ukrinform, Ventilation Systems facility destroyed in Kyiv region, 21 Sep", "https://www.ukrinform.net/rubric-economy/4166286-ventilation-systems-manufacturing-facility-destroyed-in-russian-attack-on-kyiv-region.html"),
        (38, "Ukrinform, drone hits critical infrastructure facility in Poltava region, 21 Sep", "https://www.ukrinform.net/rubric-ato/4166260-russian-drone-hits-critical-infrastructure-facility-in-poltava-region.html"),
        (39, "Kyiv Post, Pelican missile reporting and range caveat, 20 Sep", "https://www.kyivpost.com/post/84937"),
    ],
    # map incidents: (name, lon, lat, severity 1-3, label)
    incidents=[
        ("Kyiv", 30.52, 50.45, 2, "UAV debris, 1 injured"),
        ("Hlevakha", 30.30, 50.24, 3, "3 killed incl. 2 children (19 Sep)"),
        ("Boyarka", 30.30, 50.32, 1, "warehouse hit"),
        ("Semenivka", 32.58, 52.18, 1, "farm hangar destroyed"),
        ("Sumy", 34.80, 50.91, 3, "1 killed, 1 wounded"),
        ("Lozova", 36.31, 48.89, 3, "1 killed, 3 wounded, rail station hit"),
        ("Kramatorsk", 37.55, 48.72, 3, "evac centre hit, 1 killed"),
        ("Zaporizhzhia", 35.14, 47.84, 3, "6 wounded overnight, 15 buildings damaged"),
        ("Kherson", 32.62, 46.64, 3, "7 injured, wide damage"),
        ("Odesa", 30.73, 46.48, 2, "warehouse hit"),
        ("Izmail", 28.84, 45.35, 1, "MoD claim, unverified"),
        ("Mykolaiv", 31.99, 46.97, 1, "region hit, no detail"),
        ("Poltava", 34.55, 49.59, 2, "critical infrastructure hit, 13:17 late item"),
        ("Vinnytsia", 28.47, 49.23, 2, "rail infrastructure hit (20 Sep)"),
        ("Kharkiv", 36.23, 49.99, 1, "region hit"),
        ("Rivne", 26.25, 50.62, 1, "region hit"),
        ("Kropyvnytskyi", 32.26, 48.51, 1, "region hit"),
    ],
    # front axes: (name, lon, lat, clashes)
    axes=[
        ("Kostiantynivka", 37.71, 48.53, 24),
        ("Pokrovsk", 37.18, 48.28, 19),
        ("Lyman", 37.80, 48.99, 15),
        ("Kupiansk", 37.60, 49.71, 6),
        ("Huliaipole", 36.26, 47.66, 2),
        ("Orikhiv", 35.79, 47.57, 2),
        ("Sloviansk", 37.62, 48.85, 5),
        ("S. Slobozhanshchyna", 36.6, 50.3, 7),
        ("N. Slobozhanshchyna", 34.6, 51.5, 6),
    ],
)
